version: "3.9"
services:
  mysqlcliente:
    container_name: mysqlcliente
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_cliente
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - stock
    restart: always
  msvc-cliente:
    container_name: msvc-cliente
    image: juanaguero32/clientes
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DATABASE_HOST: mysqlcliente:3306
      DB_DATABASE: msvc_cliente
      DB_PASSWORD: root
      DB_USERNAME: root
      NEGOCIO_URL: ec2-54-167-29-213.compute-1.amazonaws.com:8005
    networks:
      - stock
    depends_on:
      - mysqlcliente
    restart: always


volumes:
  data-mysql:
    name: data-mysql

networks:
  stock:
